# Generated by Django 4.2 on 2023-05-09 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("about", "0002_alter_alumni_branch_alter_alumni_domain_assign_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="alumni",
            name="linkedin_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="team",
            name="linkedin_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="alumni",
            name="email_id",
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name="team",
            name="email_id",
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
